### ISSUE TITLE
Can not pull public.ecr.aws/r7q6h7y6/guard:1.0.1

### ISSUE THREAD

**Issue by nao1215** [grolston/guard-action#2] opened 2024-02-10 07:44 UTC
## About the problem
Using the following GitHub Actions, Docker image pulling fails:
```yml
name: CloudFormation Guard Action

on:
  push:
    #paths:
    #  - 'cloudformation/**'

jobs:
  cfn-guard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: grolston/guard-action@main
      with:
        data_directory: './cloudformation/'
        rule_set: "wa-Reliability-Pillar"

    - uses: grolston/guard-action@main
      with:
        data_directory: './cloudformation/'
        rule_set: "wa-Security-Pillar"
```

Error messages:
```
Build container for action use: '/home/runner/work/_actions/grolston/guard-action/main/Dockerfile'.
  /usr/bin/docker build -t 875[2](https://github.com/nao1215/rainbow/actions/runs/7852898213/job/21433168624#step:2:2)93:ecc6b48e28fd4a098d0146de46e4df64 -f "/home/runner/work/_actions/grolston/guard-action/main/Dockerfile" "/home/runner/work/_actions/grolston/guard-action/main"
  #0 building with "default" instance using docker driver
  
  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s
  
  #2 [internal] load build definition from Dockerfile
  #2 transferring dockerfile: 356B done
  #2 DONE 0.0s
  
  #3 [internal] load metadata for public.ecr.aws/r7q6h7y6/guard:1.0.1
  #3 ERROR: public.ecr.aws/r7q6h7y6/guard:1.0.1: not found
  ------
   > [internal] load metadata for public.ecr.aws/r7q6h7y6/guard:1.0.1:
  ------
  Dockerfile:2
  --------------------
     1 |     # Container image that runs your code
     2 | >>> FROM public.ecr.aws/r7q6h7y6/guard:1.0.1
     3 |     
     4 |     # Copies your code file from your action repository to the filesystem path `/` of the container
  --------------------
  ERROR: failed to solve: public.ecr.aws/r7q6h7y6/guard:1.0.1: public.ecr.aws/r7q6h7y6/guard:1.0.1: not found
  Warning: Docker build failed with exit code 1, back off 3.285 seconds before retry.
  /usr/bin/docker build -t 875293:ecc6b48e28fd4a098d0146de46e4df64 -f "/home/runner/work/_actions/grolston/guard-action/main/Dockerfile" "/home/runner/work/_actions/grolston/guard-action/main"
  #0 building with "default" instance using docker driver
  
  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s
  
  #2 [internal] load build definition from Dockerfile
  #2 transferring dockerfile: [3](https://github.com/nao1215/rainbow/actions/runs/7852898213/job/21433168624#step:2:3)56B done
  #2 DONE 0.0s
  
  #3 [internal] load metadata for public.ecr.aws/r7q6h7y6/guard:1.0.1
  #3 ERROR: public.ecr.aws/r7q6h7y6/guard:1.0.1: not found
  ------
   > [internal] load metadata for public.ecr.aws/r7q6h7y6/guard:1.0.1:
  ------
  Dockerfile:2
  --------------------
     1 |     # Container image that runs your code
     2 | >>> FROM public.ecr.aws/r7q6h7y6/guard:1.0.1
     3 |     
     4 |     # Copies your code file from your action repository to the filesystem path `/` of the container
  --------------------
  ERROR: failed to solve: public.ecr.aws/r7q6h7y6/guard:1.0.1: public.ecr.aws/r7q6h7y6/guard:1.0.1: not found
  Warning: Docker build failed with exit code 1, back off 4.79 seconds before retry.
  /usr/bin/docker build -t 875293:ecc6b48e28fd4a098d0146de46e4df64 -f "/home/runner/work/_actions/grolston/guard-action/main/Dockerfile" "/home/runner/work/_actions/grolston/guard-action/main"
  #0 building with "default" instance using docker driver
  
  #1 [internal] load build definition from Dockerfile
  #1 transferring dockerfile: 356B done
  #1 DONE 0.0s
  
  #2 [internal] load .dockerignore
  #2 transferring context: 2B done
  #2 DONE 0.0s
  
  #3 [internal] load metadata for public.ecr.aws/r7q6h7y6/guard:1.0.1
  #3 ERROR: public.ecr.aws/r7q6h7y6/guard:1.0.1: not found
  ------
   > [internal] load metadata for public.ecr.aws/r7q6h7y6/guard:1.0.1:
  ------
  Dockerfile:2
  --------------------
     1 |     # Container image that runs your code
     2 | >>> FROM public.ecr.aws/r7q6h7y6/guard:1.0.1
     3 |     
     [4](https://github.com/nao1215/rainbow/actions/runs/7852898213/job/21433168624#step:2:4) |     # Copies your code file from your action repository to the filesystem path `/` of the container
  --------------------
  ERROR: failed to solve: public.ecr.aws/r7q[6](https://github.com/nao1215/rainbow/actions/runs/7852898213/job/21433168624#step:2:6)h[7](https://github.com/nao1215/rainbow/actions/runs/7852898213/job/21433168624#step:2:7)y6/guard:1.0.1: public.ecr.aws/r7q6h7y6/guard:1.0.1: not found
Error: Docker build failed with exit code 1
```

## Expected behavior
Pull Docker image in GitHub Actions.

**Comment by grolston** [comment] 2024-02-11 04:24
We are resolving this issue and posting a new ecr link here shortly.

**Comment by BrycePC** [comment] 2024-02-12 04:50
Hi, just to see if there are any updates for when a fix may be ready? We have enjoyed using cfn-guard for quality checks, but unfortunately it has negatively-impacted our deployment and rollback pipelines with this bug.

**Comment by tyroneyellowcard** [comment] 2024-03-18 11:30
I am also getting the same error as the one posted. Is there a new ecr link?

**Comment by codyfyi** [comment] 2024-04-02 18:13
> We are resolving this issue and posting a new ecr link here shortly.

Could it be replaced with `public.ecr.aws/aws-cloudformation/cloudformation-guard:latest` now?

**Comment by grolston** [comment] 2024-04-03 04:01
Hi all, I apologize for the delay. I have added in an updated registry image reference which should bring this back running. The GitHub Action was impacted by some updates we have been working on for the AWS Guard Rules Registry. I have been working with the team to bring these updates over and finally got the process updated here. 

Please note we added some new features over in the Guard Rules Registry including cfn-nag rules and cfn-nag suppression. Due to this I am not sure how it totally impacted the rule sets that were being leveraged in the build. For more information please see the repo at: https://github.com/aws-cloudformation/aws-guard-rules-registry

**Comment by grolston** [comment] 2024-04-03 04:05
Also, I will be updating the reference one more time once I make the final changes over at the AWS Guard Rules Registry. This final update will integrate the build of the docker image with the publication of new Guard rules in the repository. The change over will be seamless for you all. 

Again, I apologize about the delay here. Please let me know any issues or if the Action is not operating as intended. We did update the suppression rules and I will try to get the documentation brought over.

**Comment by grolston** [comment] 2024-04-03 13:03
Posting here to inform you all the pipelines I had setup using this action are working now as expected.

**Comment by codyfyi** [comment] 2024-04-03 21:08
Thank you @grolston! Works great now.  It is a useful tool, thanks for making it easy to use with Github Actions.

**Comment by grolston** [comment] 2024-04-04 03:36
Marking issue as closed.

**Closed as completed by grolston** 2024-04-04 03:36 UTC
